# Generated by Django 2.1.7 on 2020-07-02 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nobles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=100)),
                ('cid', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Classroom',
                'ordering': ['cid'],
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('video_detail', models.TextField(blank=True, null=True)),
                ('video', models.FileField(upload_to='files/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning.Classroom')),
                ('homework', models.ManyToManyField(to='Nobles.Homeworks')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lectures',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning.Subjects'),
        ),
    ]
