# Generated by Django 2.1.7 on 2020-07-29 13:19

import Elearning.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cid', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Classroom',
                'ordering': ['cid'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('your_file', models.FileField(upload_to=Elearning.models.Homework.path_and_rename)),
                ('description', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning.Classroom')),
            ],
            options={
                'verbose_name_plural': 'Homeworks',
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('video_detail', models.TextField(blank=True, null=True)),
                ('video', models.FileField(upload_to='files/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning.Classroom')),
                ('homework', models.ManyToManyField(to='Elearning.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning.Subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning.Subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ManyToManyField(to='Elearning.Subject'),
        ),
    ]
