# Generated by Django 2.1.7 on 2020-07-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
