# Generated by Django 2.1.7 on 2020-08-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Elearning.Subject'),
        ),
    ]
