# Generated by Django 2.1.7 on 2020-06-09 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Elearning', '0001_initial'),
        ('Nobles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nobles.Student'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='homework',
            field=models.ManyToManyField(to='Nobles.Homeworks'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elearning.Subjects'),
        ),
    ]
