# Generated by Django 2.1.7 on 2020-07-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0002_classroom_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='homework',
            field=models.ManyToManyField(blank=True, null=True, to='Elearning.Homework'),
        ),
    ]
