# Generated by Django 2.1.7 on 2020-08-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0002_homework_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/profile_picture/'),
        ),
    ]
