# Generated by Django 2.1.7 on 2020-08-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0003_auto_20200811_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.CharField(max_length=400),
        ),
    ]
