# Generated by Django 2.1.7 on 2020-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0003_auto_20200729_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='homework',
            field=models.ManyToManyField(blank=True, to='Elearning.Homework'),
        ),
    ]
