# Generated by Django 2.1.7 on 2020-07-29 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Elearning', '0004_auto_20200729_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
