# Generated by Django 2.1.7 on 2020-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0005_classroom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.CharField(max_length=300),
        ),
    ]
