# Generated by Django 2.1.7 on 2020-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nobles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name_plural': 'Classroom'},
        ),
        migrations.AddField(
            model_name='student',
            name='cid',
            field=models.IntegerField(default=True),
        ),
    ]
