# Generated by Django 2.1.7 on 2020-04-23 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nobles', '0002_download_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('your_file', models.FileField(upload_to='files/')),
                ('description', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nobles.Student')),
            ],
        ),
    ]
