# Generated by Django 2.1.7 on 2020-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nobles', '0002_auto_20200430_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.IntegerField(default=''),
        ),
    ]
