# Generated by Django 2.1.7 on 2020-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nobles', '0003_auto_20200430_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.IntegerField(default='', null=True),
        ),
    ]
