# Generated by Django 2.1.7 on 2020-04-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nobles', '0003_homeworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworks',
            options={'verbose_name_plural': 'Homeworks'},
        ),
    ]
