# Generated by Django 2.1.7 on 2021-08-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nobles', '0003_auto_20210815_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolclassroom',
            old_name='session',
            new_name='session_start',
        ),
    ]
