# Generated by Django 2.1.7 on 2021-09-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nobles', '0004_auto_20210815_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppers',
            options={'ordering': ['-percentage'], 'verbose_name_plural': 'Toppers'},
        ),
    ]
