# Generated by Django 2.1.7 on 2020-06-01 11:44

import Nobles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nobles', '0006_auto_20200502_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworks',
            name='your_file',
            field=models.FileField(upload_to=Nobles.models.Homeworks.path_and_rename),
        ),
    ]
